imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: fr
    app.path.images: /uploads/images/voitures

framework:
    #esi: ~
    translator: { fallbacks: ['%locale%'] }
    secret: '%secret%'
    router:
        resource: '%kernel.project_dir%/app/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection:
      enabled: true
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale: '%locale%'
    trusted_hosts: ~
    session:
        # https://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'

# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_mysql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.project_dir%/var/data/data.sqlite"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path: '%database_path%'

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    spool: { type: memory }

fos_user:
    db_driver: orm
    firewall_name: main
    user_class: KZC\UsersBundle\Entity\Users
    service:
            mailer: fos_user.mailer.twig_swift
    registration:
        form:
            type: KZC\UsersBundle\Form\UsersType
        confirmation:
            enabled: false
    from_email:
        address: "%mailer_user%"
        sender_name: "%mailer_user%"
    service:
        mailer: fos_user.mailer.twig_swift
    # resetting:
    #     email:
    #         template: '@GestionKine/Resetting/email.txt.twig'
    # registration:
    #     confirmation:
    #         template:   '@FOSUser/Registration/email.txt.twig'


easy_admin:
    site_name: 'KazemiCars'
    design:
        color_scheme: 'dark'
        brand_color: '#f0c34f'
    entities:
        'Voitures':
                       class: KZC\KZCBundle\Entity\Voitures
                       list:
                            title: "Nos voitures"
                            fields:
                                   - { property: 'marque' }
                                   - { property: 'marque.modele'}
                                   - { property: 'carburant' }
                                   - { property: 'annee' }
                                   - { property: 'km' }
                                   - { property: 'options' }
                                   - { property: 'prix'}
                                   - { property: 'image', type: 'image', base_path: '/KZC/web%app.path.images%' }
                       show:
                            fields:
                                   - { property: 'image', type: 'image', base_path: '%app.path.images%' }
                       form:
                            fields:
                                   - { property: 'marque' }
                                   - { property: 'modele'}
                                   - { property: 'carburant' }
                                   - { property: 'km' }
                                   - { property: 'annee' }
                                   - { property: 'options' }
                                   - { property: 'prix'}
                                   - { property: 'imageFile', type: 'file' }
                                   - { property: 'description', type: 'ckeditor' }



        'Carburants':
                      class: KZC\KZCBundle\Entity\Carburant
                      disabled_actions: ['edit']
                      list:
                            title: "Les carburants"

        'Marques':
                      class: KZC\KZCBundle\Entity\Marques
                      list:
                            title: "Les marques"


        'Modeles':
                      class: KZC\KZCBundle\Entity\Modele
                      list:
                            title: "Les modèles"



        'Options':
                      class: KZC\KZCBundle\Entity\Options
                      list:
                            title: "Les options"


        'Users':
              class: KZC\UsersBundle\Entity\Users
              list:
                    title: "Nos Clients"
                    fields: ['FirstName', 'LastName', 'Adress', 'Number', 'Ville', 'Phone', 'Email' ]
              form:
                    fields:
                        - username
                        - email
                        - enabled
                        - lastLogin
                        # if administrators are allowed to edit users' passwords and roles, add this:
                        - { property: 'plainPassword', type: 'text', type_options: { required: false } }
                        - { property: 'roles', type: 'choice', type_options: { multiple: true, choices: { 'ROLE_USER': 'ROLE_USER', 'ROLE_ADMIN': 'ROLE_ADMIN' } } }



vich_uploader:
    db_driver: orm
    mappings:
            images:
                uri_prefix:         '%app.path.images%'
                upload_destination: '%kernel.root_dir%/../web/uploads/images/voitures'

ivory_ck_editor:
    input_sync: true
    default_config: base_config