<?php

namespace KZC\KZCBundle\Repository;

/**
 * ImagesVoitureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImagesVoitureRepository extends \Doctrine\ORM\EntityRepository
{
}
