<?php

namespace KZC\KZCBundle\Repository;

/**
 * ListVoituresRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ListVoituresRepository extends \Doctrine\ORM\EntityRepository
{
}
