services:
    # user.security.authentication_handler: 
    #     class: KZC\UsersBundle\Form\Handler\AuthenticationHandler 
    #     public: false 
    #     arguments: {"@router", "@session",'@service_container'}
    app.form.registration:
            class: KZC\UsersBundle\Form\UsersType
            tags:
                 - { name: form.type, alias: app_user_registration }
